name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version(alpha, latest)'
        required: true
        default: 'latest'
        options:
        - alpha
        - latest
jobs:
  setup:
    strategy:
      fail-fast: false
    name: Publish
    runs-on: [ubuntu-latest]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Clone target repo
        uses: actions/checkout@v2
      - name: Set node version to 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
          check-latest: true
          architecture: x64
      - name: Install rush toolchain
        run: sh ./scripts/ci.sh init
      - name: Install dependencies
        run: sh ./scripts/ci.sh install
      - name: Build
        run: sh ./scripts/ci.sh build
      - name: Release alpha
        if: ${{ inputs.version == 'alpha' }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
          npm run release:alpha
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Release latest
        if: ${{ inputs.version == 'latest' }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
          npm run release:latest
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
